-- Ensure required tables for BatikNareswara
-- Generated by audit script

-- Tabel products
CREATE TABLE IF NOT EXISTS products (
    id UUID PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT,
    description TEXT,
    original_price NUMERIC(12,2) NOT NULL,
    discount_price NUMERIC(12,2),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabel product_images
CREATE TABLE IF NOT EXISTS product_images (
    id UUID PRIMARY KEY,
    product_id UUID REFERENCES products(id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    is_primary BOOLEAN DEFAULT false
);

-- Tabel product_variants
CREATE TABLE IF NOT EXISTS product_variants (
    id UUID PRIMARY KEY,
    product_id UUID REFERENCES products(id) ON DELETE CASCADE,
    size TEXT NOT NULL,
    stock INT DEFAULT 0
);

-- Tabel stories
CREATE TABLE IF NOT EXISTS stories (
    id UUID PRIMARY KEY,
    image_or_video_url TEXT NOT NULL,
    caption TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabel outbox_messages
CREATE TABLE IF NOT EXISTS outbox_messages (
    id UUID PRIMARY KEY,
    type TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    processed_at TIMESTAMPTZ
);

-- Storage bucket and policies (Supabase)
INSERT INTO storage.buckets (id, name, public)
VALUES ('gambarBatik', 'gambarBatik', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY IF NOT EXISTS "Public Access" ON storage.objects FOR SELECT USING (bucket_id = 'gambarBatik');
CREATE POLICY IF NOT EXISTS "Authenticated Upload" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'gambarBatik' AND auth.role() = 'authenticated');
